(define (problem merged_ai_planning-problem)
 (:domain merged_ai_planning-domain)
 (:objects
   initiallocation1 initiallocation2 initiallocation3 - locationparameter
   mim8_0001 - mim8_0001aas
   order_69501bce_0d55_4f87_a56d_abe7ea17d5fa - order
 )
 (:init
              (operational planarshuttle1)
              (free planarshuttle1)
              (empty planarshuttle1)
              (resourceat planarshuttle1 initiallocation1)
              (operational planarshuttle2)
              (free planarshuttle2)
              (empty planarshuttle2)
              (resourceat planarshuttle2 initiallocation2)
              (operational planarshuttle3)
              (free planarshuttle3)
              (empty planarshuttle3)
              (resourceat planarshuttle3 initiallocation3)
              (operational imadispensingsystem)
              (free imadispensingsystem)
              (stationat imadispensingsystem dispensinglocation)
              (operational syntegonstopperingsystem)
              (free syntegonstopperingsystem)
              (stationat syntegonstopperingsystem stopperinglocation)
              (operational imaloadingsystem)
              (free imaloadingsystem)
              (stationat imaloadingsystem loadinglocation)
              (operational optimaunloadingsystem)
              (free optimaunloadingsystem)
              (stationat optimaunloadingsystem unloadinglocation)
              (operational omroncamerasystem)
              (free omroncamerasystem)
              (stationat omroncamerasystem capturelocation)
              (operational cytivacappingsystem)
              (free cytivacappingsystem)
              (step_ready mim8_0001 step_1_dispensing)
 )
 (:goal (and 
           (finished mim8_0001)
           (free planarshuttle1)
           (free planarshuttle2)
           (free planarshuttle3)
           (free imadispensingsystem)
           (free syntegonstopperingsystem)
           (free imaloadingsystem)
           (free optimaunloadingsystem)
           (free omroncamerasystem)
           (free cytivacappingsystem)
           (step_done mim8_0001 step_3_inspection)
        )
 )
)
